### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by Mozzo1000** [Mozzo1000/alpsh#6]
I see no reason to continue to use `Python 2.7`
`Python 3.x` is now either default or at least installed on most systems in use.

Latest : Python 3.6.1

**Comment by Mozzo1000** [comment]
First test and glorious fail
Can't find `history.py`, this is the history file in root directory NOT in builtins

```
Traceback (most recent call last):
  File "/usr/local/bin/alpsh", line 9, in <module>
    load_entry_point('alpsh==1.0.0', 'console_scripts', 'alpsh')()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python3.4/dist-packages/alpsh/shell.py", line 5, in <module>
    import history as history_listener
ImportError: No module named 'history'
```


Python3 apparently makes a distinction between relative and absolute imports, see [https://wiki.python.org/moin/PortingPythonToPy3k#relative-imports](https://wiki.python.org/moin/PortingPythonToPy3k#relative-imports ) for more information
